/** Autogenerated Scala Code by ANTLR v4 parser.
  * Originally Developed by: Zayd Hammoudeh (zayd.hammoudeh@sjsu.edu)
  * 
  * Course: CS252 (Spring 2016)
  * Special Thanks to Dr. Thomas Austin (thomas.austin@sjsu.edu)
  */

object compare_ops {

  private def notEqual (___0___ : Int) (___1___ : Int) :  String = (___0___, ___1___) match {
      case (x, y) =>  if(x != y)
        {
           "not equal"
        }
        else{
           "equal"
        }
  } // End of function

  private def equal (___0___ : Int) (___1___ : Int) :  String = (___0___, ___1___) match {
      case (x, y) =>  if(x == y)
        {
           "equal"
        }
        else{
           "not_equal"
        }
  } // End of function

  private def greater (___0___ : Int) (___1___ : Int) :  String = (___0___, ___1___) match {
      case (x, y) =>  if(x > y)
        {
           "greater"
        }
        else{
           "less than or equal"
        }
  } // End of function

  private def lessThan (___0___ : Int) (___1___ : Int) :  String = (___0___, ___1___) match {
      case (x, y) =>  if(x < y)
        {
           "less than"
        }
        else{
           "greater than or equal"
        }
  } // End of function

  private def greaterThanEqual (___0___ : Int) (___1___ : Int) :  String = (___0___, ___1___) match {
      case (x, y) =>  if(x >= y)
        {
           "Greater than or equal"
        }
        else{
           "Less than"
        }
  } // End of function

  private def lessThanEqual (___0___ : Int) (___1___ : Int) :  String = (___0___, ___1___) match {
      case (x, y) =>  if(x <= y)
        {
           "Less THAN or equal"
        }
        else{
           "greater than"
        }
  } // End of function

  def main(args : Array[String]){
     println (notEqual (5) (4))
     println (notEqual (3) (3))
     println (equal (5) (4))
     println (equal (4) (4))
     println (greater (4) (3))
     println (greater (3) (3))
     println (greater (3) (4))
     println (lessThan (4) (3))
     println (lessThan (3) (3))
     println (lessThan (10) (20))
     println (greaterThanEqual (-3) (-3))
     println (greaterThanEqual (-3) (-4))
     println (greaterThanEqual (-30) (-2))
     println (lessThanEqual (-3) (-3))
     println (lessThanEqual (-3) (-4))
     println (lessThanEqual (-30) (-2))
  } // End of function

}
