/** Autogenerated Scala Code by ANTLR v4 parser.
  * Originally Developed by: Zayd Hammoudeh (zayd.hammoudeh@sjsu.edu)
  * 
  * Course: CS252 (Spring 2016)
  * Special Thanks to Dr. Thomas Austin (thomas.austin@sjsu.edu)
  */

object factorial {

  private def factorial (___0___ : Int) :  Int = (___0___) match {
      case (n) =>  if(n == 0)
        {
           1
        }
        else{
           n * factorial((n -1))
        }
  } // End of function

  def main(args : Array[String]){
    println ((factorial(10)).toString())
  } // End of function

}
