/** Autogenerated Scala Code by ANTLR v4 parser.
  * Originally Developed by: Zayd Hammoudeh (zayd.hammoudeh@sjsu.edu)
  * 
  * Course: CS252 (Spring 2016)
  * Special Thanks to Dr. Thomas Austin (thomas.austin@sjsu.edu)
  */

object filter_example {

  private def zayd_filter(___0___ : INT =>  BOOL, ___1___ : List[Int]) :  List[Int] =(___0___, ___1___) match {
      case (_, Nil) =>  Nil
      case (f, ((x)::(xs))) =>  if( f(x))
      {
         ( x)::( zayd_filter(f, xs))
      }
      else{
         zayd_filter(f, xs)
      }

  } // End of function

  def main(args : Array[String]){
     println( ( filter(((xINT: Int) =>  xINT>30), List(1, 459, 43, ( -30), 34))).toString())
  } // End of function

}
