/** Autogenerated Scala Code by ANTLR v4 parser.
  * Originally Developed by: Zayd Hammoudeh (zayd.hammoudeh@sjsu.edu)
  * 
  * Course: CS252 (Spring 2016)
  * Special Thanks to Dr. Thomas Austin (thomas.austin@sjsu.edu)
  */

object get_text {

  def main(args : Array[String]){
    lazy val x = scala.io.StdIn.readLine();
     println (x)
     if((x).length() == 0)
      {
         return;
      }
      else{
         main(args)
      }
  } // End of function

}
