/** Autogenerated Scala Code by ANTLR v4 parser.
  * Originally Developed by: Zayd Hammoudeh (zayd.hammoudeh@sjsu.edu)
  * 
  * Course: CS252 (Spring 2016)
  * Special Thanks to Dr. Thomas Austin (thomas.austin@sjsu.edu)
  */

object main_print_string {

  def main(args : Array[String]){
     println ((3).toString())
     println ((4).toString())
     if(5 > 3)
      {
         println ((1).toString())
      }
      else{
         println ((0).toString())
      }
  } // End of function

}
